{% if page.type ==='picture' %}
  <script src="https://web-1256060851.file.myqcloud.com/assets/js/photos.js"></script>
  <script src="//cdn.jsdelivr.net/npm/minigrid@3.1.1/dist/minigrid.min.js"></script>
{% elif page.type === 'friends' %}
  <script src="https://web-1256060851.file.myqcloud.com/assets/js/friends.js"></script>
{% endif %}
<script src="https://web-1256060851.file.myqcloud.com/assets/js/comment-locate.js"></script>
