name: Deploy

on:
  push:
    braches: 
      - src

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
          node-version: "10.x"

    - name: Generate Hexo Pages
      run: |
        npm i -g hexo-cli
        npm i
        hexo generate

    - name: Deploy to Github
      env:
        GIT_NAME: lei2rock
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        GH_REF: github.com/lei2rock/blog
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

      run: |
        git config --global user.name $GIT_NAME
        git config --global user.email $GIT_EMAIL
        sed -i "s/GH_TOKEN/$GH_TOKEN/g" ./_config.yml
        hexo deploy -m "Build by GitHub Actions"
